### ISSUE TITLE
第二章 tex 公式，遗漏了减号

### ISSUE THREAD

**Issue by ryan4yin** [apachecn/hands-on-ml-zh#113]
位置在 “预测误差是”后面，英文原文为 "The prediction error for this
district is ![ŷ(1) – y(1) = 2,000](https://user-images.githubusercontent.com/22363274/50725503-74174180-1139-11e9-9c6d-19e39229265a.png)"

**Comment by bringtree** [comment]
thx. 开个pr  @ryan4yin

**Comment by ryan4yin** [comment]
@bringtree 好的

**Comment by bringtree** [comment]
#114
