### ISSUE TITLE
第二版上市了

### ISSUE THREAD

**Issue by PEGASUS1993** [apachecn/hands-on-ml-zh#116]
Hands on Machine Learning with Scikit-Learning,Keras&Tensorflow. 英文版第二版已经上市了，水友们继续翻译一波？

**Comment by PeterHo** [comment]
有电子版了吗

**Comment by PEGASUS1993** [comment]
> 有电子版了吗

有.ipynb 文件源代码了，我实在BUPT 陈光老师微博下面看到的

**Comment by wizardforcel** [comment]
更新起来应该很简单吧。。。

**Comment by PEGASUS1993** [comment]
> 更新起来应该很简单吧。。。

第二版github链接 https://github.com/ageron/handson-ml2  这是应该英文作者自己的github  
图书详细介绍  https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/ 
请飞龙大佬过目~~~

**Comment by wizardforcel** [comment]
@PEGASUS1993 第一部分没变，第二部分改成了 TFE 和 Keras 实现，但是还没放出来。。。再等等吧。

**Comment by PEGASUS1993** [comment]
> @PEGASUS1993 第一部分没变，第二部分改成了 TFE 和 Keras 实现，但是还没放出来。。。再等等吧。

收到收到。
