### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by tabeworks** [apachecn/hands-on-ml-zh#117]
感谢翻译。

1.Page 26, 表1-1 发过->法国
2.Page 62, "跟喜欢和数字打交道"->“更喜欢和数字打交道”
3.Page 83, “的克隆版本上进行训，”->“的克隆版本上进行训练，”
4.Page 84，“第五航第三列”->“第五行第三列”
5.Page 92，“OvO策略的主要有点”->“OVO策略的主要优点”

**Comment by bringtree** [comment]
@tab thx, 你开个pr。我合并下。
