### ISSUE TITLE
Markdown 中的公式为啥都是图片，而不用 tex 直接写呢？

### ISSUE THREAD

**Issue by qiwihui** [apachecn/hands-on-ml-zh#130]

**Comment by jiangzhonglian** [comment]
老哥，这个应该是这个模版网站自动变异，生成的图片

**Comment by qiwihui** [comment]
@jiangzhonglian 我指的是在 Markdown 中写公式的时候，都是引用了图片，比如 [选择性能指标](https://github.com/apachecn/hands-on-ml-zh/blob/master/docs/2.%E4%B8%80%E4%B8%AA%E5%AE%8C%E6%95%B4%E7%9A%84%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E9%A1%B9%E7%9B%AE.md#%E9%80%89%E6%8B%A9%E6%80%A7%E8%83%BD%E6%8C%87%E6%A0%87) 下的公式，使用的是 `![](../images/chapter_2/e-2-1.png)` 这样的方式，而不是用 tex 直接写成

```tex
$$
RMSE(X, h) = \sqrt{\frac{1}{m} \sum_{i=1}^{m}(h(x^{(i)})-y^{(i)})^2)}
$$
```

输出结果对比：

![image](https://github.com/apachecn/hands-on-ml-zh/raw/master/images/chapter_2/e-2-1.png)

![image](https://user-images.githubusercontent.com/3297411/52937008-de5a0d80-3398-11e9-9a26-2edffcaaf40f.png)

**Comment by bringtree** [comment]
@qiwihui  github的markdown 不支持。

**Comment by qiwihui** [comment]
如果用 gitbook 作为主要分发的话其实也是可以支持公式的。
多谢！

**Comment by jiangzhonglian** [comment]
gitbook 算一个编译网站的工具，我们用的不是gitbook，好像是 mkdocs，会自动生成图片

**Comment by qiwihui** [comment]
噢，好的。
